blank_issues_enabled: true
contact_links:
  - name: Pikifen Discord server
    url: https://discord.gg/qbhz4u3
    about: Instead of writing an issue, you can report the problem in the Pikifen Discord server.
