.PHONY: clean All

All:
	@echo "----------Building project:[ Pikifen - Debug ]----------"
	@"$(MAKE)" -f  "Pikifen.mk"
clean:
	@echo "----------Cleaning project:[ Pikifen - Debug ]----------"
	@"$(MAKE)" -f  "Pikifen.mk" clean
