.PHONY: clean All

All:
	@echo "----------Building project:[ Pikmin_fangame_engine - Debug ]----------"
	@"$(MAKE)" -f  "Pikmin_fangame_engine.mk"
clean:
	@echo "----------Cleaning project:[ Pikmin_fangame_engine - Debug ]----------"
	@"$(MAKE)" -f  "Pikmin_fangame_engine.mk" clean
