/*
 * Copyright (c) Andre 'Espyo' Silva 2013-2017.
 * The following source file belongs to the open-source project
 * Pikmin fangame engine. Please read the included
 * README and LICENSE files for more information.
 * Pikmin is copyright (c) Nintendo.
 *
 * === FILE DESCRIPTION ===
 * Globally accessible variables.
 */

#include <limits.h>

#include "area_editor.h"
#include "vars.h"
#include "const.h"

using namespace std;

ALLEGRO_BITMAP* bmp_bubble = NULL;
ALLEGRO_BITMAP* bmp_checkbox_check = NULL;
ALLEGRO_BITMAP* bmp_cursor = NULL;
ALLEGRO_BITMAP* bmp_day_bubble = NULL;
ALLEGRO_BITMAP* bmp_enemy_spirit = NULL;
ALLEGRO_BITMAP* bmp_group_move_arrow = NULL;
ALLEGRO_BITMAP* bmp_hard_bubble = NULL;
ALLEGRO_BITMAP* bmp_icon = NULL;
ALLEGRO_BITMAP* bmp_idle_glow = NULL;
ALLEGRO_BITMAP* bmp_info_spot = NULL;
ALLEGRO_BITMAP* bmp_message_box = NULL;
ALLEGRO_BITMAP* bmp_mouse_cursor = NULL;
ALLEGRO_BITMAP* bmp_mouse_button_icon[3] = {NULL, NULL, NULL};
ALLEGRO_BITMAP* bmp_mouse_wd_icon = NULL;
ALLEGRO_BITMAP* bmp_mouse_wu_icon = NULL;
ALLEGRO_BITMAP* bmp_nectar = NULL;
ALLEGRO_BITMAP* bmp_no_pikmin = NULL;
ALLEGRO_BITMAP* bmp_notification = NULL;
ALLEGRO_BITMAP* bmp_number_bubble = NULL;
ALLEGRO_BITMAP* bmp_pikmin_spirit = NULL;
ALLEGRO_BITMAP* bmp_shadow = NULL;
ALLEGRO_BITMAP* bmp_smack = NULL;
ALLEGRO_BITMAP* bmp_smoke = NULL;
ALLEGRO_BITMAP* bmp_sparkle = NULL;
ALLEGRO_BITMAP* bmp_sun = NULL;
ALLEGRO_BITMAP* bmp_ub_spray = NULL;
ALLEGRO_BITMAP* bmp_us_spray = NULL;
ALLEGRO_BITMAP* bmp_wave_ring = NULL;

sample_struct sfx_attack;
sample_struct sfx_camera;
sample_struct sfx_louie_whistle;
sample_struct sfx_louie_name_call;
sample_struct sfx_olimar_whistle;
sample_struct sfx_olimar_name_call;
sample_struct sfx_president_whistle;
sample_struct sfx_president_name_call;
sample_struct sfx_pikmin_attack;
sample_struct sfx_pikmin_called;
sample_struct sfx_pikmin_carrying;
sample_struct sfx_pikmin_carrying_grab;
sample_struct sfx_pikmin_caught;
sample_struct sfx_pikmin_dying;
sample_struct sfx_pikmin_held;
sample_struct sfx_pikmin_idle;
sample_struct sfx_pluck;
sample_struct sfx_pikmin_plucked;
sample_struct sfx_pikmin_thrown;
sample_struct sfx_switch_pikmin;
sample_struct sfx_throw;

vector<string> animation_editor_history;
ALLEGRO_FONT* allegro_font = NULL;
vector<vector<ALLEGRO_BITMAP*> > area_images;
float area_images_scale = 1.0;
int area_image_size = 0;
float area_images_x1 = 0;
float area_images_y1 = 0;
timer area_title_fade_timer(AREA_TITLE_FADE_DURATION);
float area_time_passed = 0;
string area_to_load;
vector<unsigned int> berries;
bmp_manager bitmaps;
ALLEGRO_BITMAP* bmp_error = NULL;
vector<bridge*> bridges;
button_manager buttons;
float cam_final_x = 0;
float cam_final_y = 0;
float cam_final_zoom = 1.0;
float cam_x = 0;
float cam_y = 0;
float cam_zoom = 1.0;
ALLEGRO_COLOR carrying_color_move = al_map_rgb(255, 255, 255);
ALLEGRO_COLOR carrying_color_stop = al_map_rgb(96, 192, 192);
float carrying_speed_base_mult = 0.5;
float carrying_speed_max_mult = 0.8;
float carrying_speed_weight_mult = 0.0004;
size_t click_control_id = INVALID;
mob* closest_group_member = NULL;
vector<vector<control_info> > controls;
area_data cur_area_data;
size_t cur_leader_nr = 0;
leader* cur_leader_ptr = nullptr;
string cur_message;
size_t cur_message_char = 0;
timer cur_message_char_timer(0);
size_t cur_message_section = 0;
ALLEGRO_BITMAP* cur_message_speaker = NULL;
vector<size_t> cur_message_stopping_chars;
unsigned char cur_game_state_nr = GAME_STATE_GAME;
float cur_sun_strength = 1;
float cursor_angle = 0;
float cursor_height_diff_light = 0;
float cursor_invalid_effect = 0;
float cursor_max_dist = 200.0;
movement_struct cursor_movement;
timer cursor_save_timer(CURSOR_SAVE_INTERVAL);
float cursor_spin_speed = M_PI * 4.0f;
vector<point> cursor_spots;
float cursor_x = 0;
float cursor_y = 0;
map<string, particle_generator> custom_particle_generators;
unsigned int day = 1;
float day_minutes = 60 * 7;
float day_minutes_end = 60 * 19;
float day_minutes_per_irl_sec = 2;
float day_minutes_start = 60 * 7;
double delta_t = 0;
string dev_tool_area_image_name;
bool dev_tool_area_image_shadows = true;
int dev_tool_area_image_size = 2048;
string dev_tool_auto_start_option;
string dev_tool_auto_start_mode;
bool dev_tool_change_speed = false;
float dev_tool_change_speed_mult = 2.0;
mob* dev_tool_info_lock = NULL;
pikmin_type* dev_tool_last_pikmin_type = NULL;
bool dev_tool_show_mouse_coords = false;
unsigned char dev_tool_keys[10];
ALLEGRO_DISPLAY* display = NULL;
bool draw_cursor_trail = true;
float editor_backup_interval = DEF_EDITOR_BACKUP_INTERVAL;
map<string, enemy_type*> enemy_types;
vector<enemy*> enemies;
fade_manager fade_mgr;
ALLEGRO_FONT* font_main = NULL;
ALLEGRO_FONT* font_area_name = NULL;
ALLEGRO_FONT* font_counter = NULL;
unsigned int font_counter_h = 0;
unsigned int font_main_h = 0;
ALLEGRO_FONT* font_value = NULL;
unsigned int framerate_counter = 30;
timer framerate_update_timer(0.3f);
int game_fps = DEF_FPS;
string game_name;
map<size_t, game_state*> game_states;
string game_version;
vector<gate*> gates;
map<string, gate_type*> gate_types;
float group_move_angle = 0;
vector<float> group_move_arrows;
float group_move_intensity = 0;
timer group_move_next_arrow_timer(GROUP_MOVE_ARROWS_INTERVAL);
bool group_move_cursor = false;
float group_move_task_range = 0;
movement_struct group_movement;
vector<vector<float> > group_spots_x;
vector<vector<float> > group_spots_y;
map<string, hazard> hazards;
float hud_coords[N_HUD_ITEMS][4];
float idle_task_range = 50;
string info_print_text;
timer info_print_timer =
    timer(
        INFO_PRINT_DURATION,
[] () { info_print_text.clear(); }
    );
float info_spot_trigger_range = 64.0f;
vector<info_spot*> info_spots;
bool is_game_running = true;
map<ALLEGRO_JOYSTICK*, int> joystick_numbers;
vector<leader*> leaders;
movement_struct leader_movement;
map<string, leader_type*> leader_types;
ALLEGRO_BITMAP* loading_text_bmp = NULL;
ALLEGRO_BITMAP* loading_subtext_bmp = NULL;
map<string, liquid> liquids;
float maturity_power_mult = 0.1f;
float maturity_speed_mult = 0.1f;
size_t max_particles = 200;
size_t max_pikmin_in_field = 100;
float message_char_interval = 0.02f;
map<string, mob_type*> misc_mob_types;
ALLEGRO_MIXER* mixer = NULL;
mob_category_manager mob_categories;
vector<mob*> mobs;
float mouse_cursor_x = scr_w / 2 + 10;
float mouse_cursor_y = scr_h / 2;
bool mouse_cursor_valid = true;
bool mouse_moves_cursor[4] = {true, false, false, false};
size_t nectar_amount = 5;
vector<nectar*> nectars;
float next_pluck_range = 160.0f;
bool no_error_logs_today = true;
float onion_open_range = 64.0f;
map<string, onion_type*> onion_types;
vector<onion*> onions;
unsigned char particle_quality = 2;
particle_manager particles(0);
bool paused = false;
map<string, pellet_type*> pellet_types;
vector<pellet*> pellets;
vector<point> precipitation;
timer precipitation_timer(0);
float pikmin_grab_range = 64.0f;
map<pikmin_type*, unsigned long> pikmin_in_onions;
vector<pikmin*> pikmin_list;
map<string, pikmin_type*> pikmin_types;
float pluck_range = 30.0f;
bool pretty_whistle = true;
double prev_frame_time = 0;
float prev_group_move_intensity = 0;
bool ready_for_input = false;
bool reset_delta_t = true;
int scr_h = DEF_SCR_H;
int scr_w = DEF_SCR_W;
sector_types_manager sector_types;
unsigned int selected_spray = 0;
unsigned char ship_beam_ring_color[3] = {0, 0, 0};
bool ship_beam_ring_color_up[3] = {true, true, true};
map<string, ship_type*> ship_types;
vector<ship*> ships;
bool show_framerate = false;
bool smooth_scaling = true;
single_animation_suite spark_animation;
map<string, mob_type*> spec_mob_types;
vector<unsigned long> spray_amounts;
vector<spray_type> spray_types;
map<string, status_type> status_types;
map<string, treasure_type*> treasure_types;
vector<treasure*> treasures;
ALLEGRO_VOICE* voice = NULL;
map<string, weather> weather_conditions;
float whistle_dot_radius[6] = { -1, -1, -1, -1, -1, -1 };
float whistle_fade_radius = 0;
timer whistle_fade_timer(WHISTLE_FADE_TIME);
float whistle_growth_speed = 180.0f;
timer whistle_next_dot_timer(WHISTLE_DOT_INTERVAL);
timer whistle_next_ring_timer(WHISTLE_RINGS_INTERVAL);
float whistle_radius = 0;
vector<unsigned char> whistle_ring_colors;
unsigned char whistle_ring_prev_color = 0;
vector<float> whistle_rings;
bool whistling = false;
bool window_position_hack = false;
float zoom_max_level = 2.0f;
float zoom_mid_level = 1.0f;
float zoom_min_level = 0.5f;
