name: Compile for Windows

on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup Nuget
      uses: nuget/setup-nuget@v2.0.0
      
    - name: Restore Nuget packages
      run: nuget restore Source\visual_studio_2022\Pikifen.sln

    - name: Build app for release
      run: msbuild Source\visual_studio_2022\Pikifen.vcxproj -t:rebuild -verbosity:n -property:Configuration=Release -property:Platform=x64
      
    - name: Copy Files to build directory
      run: |
        new-item ${{ github.workspace }}\build -itemtype directory
        copy-item -Path ${{ github.workspace }}\Source\visual_studio_2022\x64\Release\Pikifen.exe -Destination ${{ github.workspace }}\build -PassThru
    
    - name: Publish artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: Pikifen
        path: ${{ github.workspace }}\build\
